name: Xenon Clone CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build verification
      run: |
        # Verify HTML is valid
        npx html-validate index.html
        # Check for console errors (basic static analysis)
        node -c js/*.js
        # Verify CSS syntax
        npx stylelint css/*.css

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        cname: xenon-clone.dev # Optional: custom domain

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install ESLint
      run: |
        npm install -g eslint
        npm install -g html-validate
        npm install -g stylelint

    - name: Lint JavaScript
      run: eslint js/*.js

    - name: Lint HTML
      run: html-validate index.html

    - name: Lint CSS
      run: stylelint css/*.css
